export { default as AdminSchema } from "./admin.js";
export { default as TokenStudentSchema } from "./tokenstudent.js";
export { default as TokenTutorSchema } from "./tokentutor.js";
export { default as TokenAdminSchema } from "./tokenadmin.js";
export { default as StudentRegisterSchema } from "./studentregister.js";
export { default as StudentInformationSchema } from "./studentinformation.js";
export { default as StudentWalletSchema } from "./studentwallet.js";
export { default as StudentQuestionsSchema } from "./studentquestions.js";
export { default as MainQuestionsSchema } from "./mainquestions.js";
export { default as TutorQuestionsSchema } from "./tutorquestions.js";
export { default as TutorSubjectsSchema } from "./tutorsubjects.js";
export { default as TutorPersonalSchema } from "./tutorpersonal.js";
export { default as TutorProfessionalSchema } from "./tutorprofessional.js";
export { default as TutorRegisterSchema } from "./tutorregister.js"
export { default as TutorBankDetailsSchema } from "./tutorbankdetails.js";
export { default as TutorWalletSchema } from "./tutorwallet.js";
export { default as ImageSchema } from "./image.js"
export { default as TutorDocumentSchema } from "./tutordocument.js";
export { default as TutorTimingSchema } from "./tutortiming.js";